/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/examples/log': RouteRecordInfo<'/examples/log', '/examples/log', Record<never, never>, Record<never, never>>,
    '/examples/noAuth': RouteRecordInfo<'/examples/noAuth', '/examples/noAuth', Record<never, never>, Record<never, never>>,
    '/examples/quickForm/': RouteRecordInfo<'/examples/quickForm/', '/examples/quickForm', Record<never, never>, Record<never, never>>,
    '/examples/role/': RouteRecordInfo<'/examples/role/', '/examples/role', Record<never, never>, Record<never, never>>,
    '/examples/user': RouteRecordInfo<'/examples/user', '/examples/user', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
